import numpy as np
arry1=np.array([[1,2,3],
                [1,2,3]])
print(arry1)
print(arry1.ndim)
print(arry1.size)
print(arry1.shape)
print(type(arry1))
print(arry1.dtype)
print("----------------------------------NumPy Array Creation-------------------------")
zeroarray=np.zeros((3,4))
print(zeroarray)
onesarray=np.ones((2,2))
print(onesarray)
arry2=np.array([[1,2,3,4],[1,2,3,4]],dtype=float)
print(arry2)
d=np.full((2,2),4,dtype=complex)
print(d)
e=np.random.random((2,2))
print(e)